article/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name = "article"


urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
    
]

django_emreblog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('user/',include("user.urls")),
    path('articles/',include("article.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name = "Yazar")
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField(verbose_name = "İçerik")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name = "Makale",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name="İsim")
    comment_content = models.CharField(max_length = 200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.



def articles(request):
    keyword = request.GET.get("keyword")
    
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    
    
    
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})



def index(request):
    return render(request,"index.html")


def about(request):
    return render(request,"about.html")


@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles" : articles
    }
    
    return render(request,"dashboard.html",context)


@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Oluşturuldu...")
        return redirect("article:dashboard")
    
    
    return render(request,"addarticle.html",{"form":form})



def detail(request,id):
    #Bu komut kullanıldığında eğer makale yoksa ekrana boş safa dönüyor.
    #article = Article.objects.filter(id = id).first
    article = get_object_or_404(Article,id = id)
    
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})


@login_required(login_url="user:login")
def updateArticle(request,id):
    
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi...")
        return redirect("article:dashboard")
    
    return render(request,"update.html",{"form":form})



@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi...")
    return redirect("article:dashboard")



def  addComment(request,id):
    article = get_object_or_404(Article,id = id)
    
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        
        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article
        newComment.save()
    
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}

{% block body %}
    <h3>Hakkımda</h3>
    <hr>
    <p>
        Merhaba, ben Yunus Emre YÜKSEK.
    </p>

{% endblock body %}
    

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>

        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "Submit" class = "btn btn-danger">Makale Oluştur</button>
        </form>

    </div>
</div>





{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class = "row">
    <div class="col-md-10 offset-md-3">
        <div class = "col-lg-8">
            <h3>Makaleler</h3>    
            <hr>
        </div>
    </div>
</div>
<div class = "row">
    <div class="col-md-10 offset-md-3">
        <div class = "col-lg-8">
            <form>
                {% csrf_token %}
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
                <button type="submit" class="btn btn-danger">Ara</button>
                <br><br>
            </form>
        </div>
    </div>
</div>


{% if articles %}

{% for article in articles %}

<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <a href="{% url 'article:detail' article.id %}"><h2 class="fw-bolder mb-1">{{article.title}}</h2></a>
                    <!--Author-->
                    <p>
                        "{{article.author.username}}" tarafından yayınlandı.
                    </p>
                    
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                    
                </header>
                <!-- Preview image figure-->
                
                {% if article.article_image %}
                    <a href="{% url 'article:detail' article.id %}"><figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="" /></figure></a>
                    
                {% endif %}
                    
                <!-- Post content-->
                <section class="mb-5">
                    <p class="lead">
                        {{article.content|safe|truncatewords:50}}
                    </p>
                </section>
            </article>
            
        <a style = "float : right" href="{% url 'article:detail' article.id %}" class = "btn btn-danger">Devamını Oku</a>
        </div>
        <br><br><hr><br>
    </div>
</div>

{% endfor %}

{% else %}
<br>
<div class = "row">
    <div class="col-md-10 offset-md-3">
        <div class = "col-lg-8">
            <div class = "alert alert-danger">
                Makale Bulunamadı...
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock body %}
    

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>

<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>
<hr>

{% if articles %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles %}
            <tr>
                <th scope="row">{{article.id}}</th>
                <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                <td>{{article.author.username}}</td>
                <td>{{article.created_date}}</td>
                <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
                <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<div class = "alert alert-danger">Henüz bir makaleniz bulunmuyor...</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h2 class="fw-bolder mb-1">{{article.title}}</h2>
                <!--Author-->
                <p>
                    "{{article.author.username}}" tarafından yayınlandı.
                </p>
                
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                
            </header>
            <!-- Preview image figure-->
            
            {% if article.article_image %}
                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="" /></figure>

            
                
            {% endif %}
                
            <!-- Post content-->
            <section class="mb-5">
                <p class="lead">
                    {{article.content|safe}}
                </p>
            </section>
        </article>
        <hr>

        <!-- Comments -->
        <h4>Yorumlar</h4>
        <br><br>
        {% if comments %}
            {% for comment in comments %}
                <div class="media mb-4">
                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                    <div class="media-body">
                        <h5 class="fw-bold">{{comment.comment_author}}</h5>
                        {{comment.comment_date}} <br>
                        {{comment.comment_content}}
                    </div>
                </div>
            {% endfor %}
            
        {% else %}
            <div class = "alert alert-danger">
                Bu makaleye herhangi bir yorum yapılmamış, ilk yorum yapan siz olun!
            </div>
        {% endif %}
            

        <div class="card my-4">
            <h5 class = "card-header">Yorum Ekle</h5>
            <div class="card-body">
                <form method="POST" action="{% url 'article:comment' article.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">İsim</label>
                        <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Girin">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput">Yorum</label>
                        <textarea name = "comment_content" class="form-control" rows="3" placeholder="Tartışmaya katılın ve bir yorum bırakın!"></textarea>
                    </div>
                    <button type="submit" class = "btn btn-danger">Ekle</button>
                </form>
            </div>
        </div>




    </div>
    
</div>





{% endblock body %}

templates/index.html
{% extends 'layout.html' %}

{% block body %}
    
<div class="jumbotron text-center">

    <h3>Yunus Emre Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogda geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz ve insanlara yardımcı olabilirsiniz.</p>

</div>



<p>
    
    {% if request.user.is_authenticated %}
        Giriş Yapılmış, {{request.user.username}}
    {% else %}
        Giriş Yapılmamış
    {% endif %}
        

</p>

{% endblock body %}
    

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Emre Blog</title>
</head>
<body>
    
    {% include "includes/navbar.html" %}

    <div style="margin-top : 100px; margin-bottom:100px;" class = "container">

        {% if messages %}
            {% for message in messages %}
            {% if message.tags == "info" %}
                <div class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
            {% endfor %}
        {% endif %}

        {% block body %}
          
        {% endblock body %}
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>


</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>

        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "Submit" class = "btn btn-danger">Giriş Yap</button>
        </form>

    </div>
</div>
{% endblock body %}
    

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>

        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "Submit" class = "btn btn-danger">Kayıt Ol</button>
        </form>

    </div>
</div>
{% endblock body %}
    

templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>

        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "Submit" class = "btn btn-danger">Makale Güncelle</button>
        </form>

    </div>
</div>





{% endblock body %}